In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

In [2]:
dataset = pd.read_csv("insurance.csv")
dataset

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [3]:
dataset = pd.get_dummies(dataset,drop_first=True)
dataset

,age,bmi,children,charges,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,False,True,False,False,True
1,18,33.770,1,1725.55230,True,False,False,True,False
2,28,33.000,3,4449.46200,True,False,False,True,False
3,33,22.705,0,21984.47061,True,False,True,False,False
4,32,28.880,0,3866.85520,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,True,False,True,False,False
1334,18,31.920,0,2205.98080,False,False,False,False,False
1335,18,36.850,0,1629.83350,False,False,False,True,False
1336,21,25.800,0,2007.94500,False,False,False,False,True
1337,61,29.070,0,29141.36030,False,True,True,False,False

In [4]:
x=dataset[['age','bmi','children','sex_male','smoker_yes','region_northwest','region_southeast','region_southwest']]
y=dataset['charges']

In [5]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=24)

In [6]:
x_train

,age,bmi,children,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
132,53,35.900,2,False,False,False,False,True
508,24,25.270,0,False,False,False,False,False
422,40,32.775,1,True,True,False,False,False
613,34,19.000,3,False,False,False,False,False
1111,38,38.390,3,True,True,False,True,False
...,...,...,...,...,...,...,...,...
145,29,38.830,3,False,False,False,True,False
343,63,36.765,0,True,False,False,False,False
192,25,25.740,0,True,False,False,True,False
899,19,22.515,0,False,False,True,False,False
418,64,39.160,1,True,False,False,True,False

In [7]:
y_train

132     11163.56800
508      3044.21330
422     39125.33225
613      6753.03800
1111    41949.24410
           ...
145      5138.25670
343     13981.85035
192      2137.65360
899      2117.33885
418     14418.28040
Name: charges, Length: 1070, dtype: float64

In [8]:
sc = StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [16]:
para_grid = {'criterion':['squared_error','absolute_error','poisson'], 'max_features': ['auto','sqrt','log2'], 'n_estimators':[10,100]}

In [17]:
grid = GridSearchCV(RandomForestRegressor(),para_grid, refit=True , verbose = 3 ,n_jobs = -1)
grid.fit(x_train , y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

/home/lokesh/jupyter-env/lib/python3.14/site-packages/sklearn/model_selection/_validation.py:493: FitFailedWarning:
30 fits failed out of a total of 90.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
18 fits failed with the following error:
Traceback (most recent call last):
  File "/home/lokesh/jupyter-env/lib/python3.14/site-packages/sklearn/model_selection/_validation.py", line 855, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lokesh/jupyter-env/lib/python3.14/site-packages/sklearn/base.py", line 1393, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/lokesh/jupyter-env/lib/python3.14/site-packages/sklearn/base.py", line 554, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/lokesh/jupyter-env/lib/python3.14/site-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
12 fits failed with the following error:
Traceback (most recent call last):
  File "/home/lokesh/jupyter-env/lib/python3.14/site-packages/sklearn/model_selection/_validation.py", line 855, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lokesh/jupyter-env/lib/python3.14/site-packages/sklearn/base.py", line 1393, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/lokesh/jupyter-env/lib/python3.14/site-packages/sklearn/base.py", line 554, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/lokesh/jupyter-env/lib/python3.14/site-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/home/lokesh/jupyter-env/lib/python3.14/site-packages/sklearn/model_selection/_search.py:1237: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.80054775 0.82269546 0.81778152 0.83922043
        nan        nan 0.79859945 0.82208719 0.81868046 0.83917517
        nan        nan 0.80344065 0.82352266 0.81805581 0.83910769]
  warnings.warn(

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [18]:

re=grid.cv_results_ 
print("TheR_scorevalueforbestparameter{}:".format(grid.best_params_))

TheR_scorevalueforbestparameter{'criterion': 'squared_error', 'max_features': 'log2', 'n_estimators': 100}:

In [19]:
table=pd.DataFrame.from_dict(re)

In [20]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002017,0.000150,0.000000,0.000000,squared_error,auto,10,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
1,0.001977,0.000321,0.000000,0.000000,squared_error,auto,100,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
2,0.140047,0.050687,0.006717,0.000356,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.762444,0.813385,0.801981,0.800706,0.824223,0.800548,0.020877,11
3,0.459252,0.096386,0.031348,0.002215,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.795766,0.842740,0.815887,0.820513,0.838572,0.822695,0.016912,5
4,0.060644,0.014626,0.006708,0.000862,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.810272,0.822059,0.814671,0.815573,0.826332,0.817782,0.005698,9
5,0.441966,0.020287,0.034510,0.004652,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.819780,0.858663,0.836863,0.831282,0.849514,0.839220,0.013642,1
6,0.002487,0.001202,0.000000,0.000000,absolute_error,auto,10,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
7,0.002502,0.001365,0.000000,0.000000,absolute_error,auto,100,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
8,0.143489,0.037495,0.009823,0.003783,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.800131,0.799095,0.784067,0.788804,0.820900,0.798599,0.012705,12
9,0.830961,0.150358,0.024601,0.007477,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.805209,0.848443,0.815364,0.806770,0.834649,0.822087,0.016835,6
10,0.108131,0.002255,0.005501,0.000187,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.800972,0.828676,0.817792,0.811168,0.834794,0.818680,0.012086,7
11,0.757924,0.164572,0.018607,0.007111,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.826436,0.855943,0.830756,0.830272,0.852468,0.839175,0.012412,2
12,0.001446,0.000073,0.000000,0.000000,poisson,auto,10,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
13,0.001762,0.000146,0.000000,0.000000,poisson,auto,100,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
14,0.043802,0.001564,0.005313,0.000185,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.782814,0.813696,0.790200,0.795063,0.835430,0.803441,0.018971,10
15,0.338188,0.055362,0.021777,0.003802,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.786377,0.843135,0.819516,0.825090,0.843496,0.823523,0.020890,4
16,0.030908,0.000916,0.003987,0.000209,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.798237,0.840516,0.817032,0.802572,0.831922,0.818056,0.016311,8
17,0.267994,0.037156,0.013355,0.002039,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.815696,0.858444,0.837219,0.833405,0.850775,0.839108,0.014793,3

In [21]:
y_pred=grid.predict(x_test)
y_pred

array([42652.0526136 , 12134.6267958 ,  6364.7135287 , 40322.026526  ,
        8532.4418984 , 20622.2745542 ,  2291.331805  , 14544.1667671 ,
        6657.4853581 , 16495.5163626 , 12814.6616867 ,  2796.63626822,
       12598.2614567 ,  9069.0763642 ,  3151.9449275 , 24943.8854446 ,
       33662.8841925 ,  2357.2453689 ,  3121.4035542 , 34543.3495384 ,
       11882.9093425 , 28998.82666   , 23917.5543739 , 36212.786049  ,
        3510.5093006 , 14034.0335268 ,  9261.1026318 , 43173.0638315 ,
       15632.0990252 , 14101.9784987 , 48549.1815344 ,  7706.7947778 ,
        6798.6233417 ,  4200.6850833 ,  9988.8976753 , 10948.6504063 ,
       17801.4586683 ,  6310.5488058 , 14699.8963005 , 12363.8126528 ,
        4616.4253346 , 16793.1413172 ,  7893.2242416 ,  5057.6024747 ,
       32269.0044274 , 10381.5689675 ,  6524.9090345 , 26592.7731092 ,
        7939.4639683 ,  2550.2357187 ,  8455.0170742 ,  9638.0401717 ,
        5776.7124364 ,  7722.6713851 , 13332.7714125 , 44122.6866371 ,
       42266.0392099 , 44899.9661419 ,  3514.67960169,  6427.0398331 ,
       12464.4757487 ,  5514.7450037 ,  5070.7590324 ,  5775.0300886 ,
        6033.8177062 ,  9578.7798029 ,  5037.649036  ,  6139.2966995 ,
        2828.5290537 , 12285.1496472 ,  6112.7582177 , 45177.4012009 ,
        4044.5163106 ,  3288.3681329 ,  3245.8242234 , 11167.7326219 ,
       27666.1975207 ,  7025.5423166 , 11910.9150585 , 13485.5880282 ,
        6389.986129  , 31572.1892121 ,  6043.1751845 , 10588.3340795 ,
       35125.1143144 ,  7261.3091165 ,  9479.8582185 ,  8664.1420002 ,
        8889.6003484 ,  1751.7836535 , 13238.9344227 , 12245.6049945 ,
       41995.0863579 ,  4430.8650247 ,  4157.433799  , 37801.5211787 ,
        6857.5174039 , 14208.3620578 ,  2259.6784205 ,  2512.93645104,
        4238.7889211 ,  7296.8742737 ,  9122.4576119 ,  4039.453585  ,
        1731.1621832 ,  4725.0054519 , 40893.615599  ,  7101.7971349 ,
       12786.9215759 ,  2641.9826265 , 11765.5933071 , 16637.5848634 ,
       17307.6777454 ,  4009.8033522 , 17678.2566283 ,  9541.9642723 ,
       10906.5891171 , 33095.8474089 , 14296.4141287 , 37565.9030985 ,
        3186.4952813 , 11944.8216161 ,  9542.6211304 ,  6887.6680533 ,
       10062.9317058 , 18651.9482766 ,  8755.0227009 ,  9751.4411655 ,
        8025.724863  ,  8952.3267344 , 11964.237277  ,  8593.9107579 ,
       16686.0598065 , 11880.0195069 , 45175.2876499 ,  3934.8402994 ,
        7831.9634558 ,  7775.6643845 ,  5733.1128233 , 10966.293055  ,
       19103.0443789 ,  5870.6595089 , 10240.5730054 , 29355.6717691 ,
        5556.2342117 , 10960.3143915 ,  4799.53030829, 44841.5630983 ,
       13959.0528609 ,  7930.6831465 ,  2636.967736  ,  9598.307872  ,
        6476.8628887 , 12696.1040081 , 10100.3957596 ,  6711.2095127 ,
        5432.8061391 ,  4814.8818465 , 37458.5465383 ,  3009.9130175 ,
       12620.0656701 , 37952.052198  , 35831.577758  ,  6454.7100272 ,
       40756.4898196 ,  6564.3439105 , 14198.5386207 ,  3005.85603429,
        5695.1153308 , 10141.8324196 , 11668.2523631 ,  3898.9292963 ,
        6461.20272988,  4205.9041432 ,  8862.8066741 , 11635.794888  ,
        9023.2059824 ,  4410.53745239,  5574.269995  ,  5654.549393  ,
       44230.8390834 , 12724.2103292 ,  9171.5618013 , 12631.1171046 ,
        9540.0976688 ,  9270.0066913 , 30757.8997619 , 45785.2459867 ,
       28527.6402214 , 18943.2956031 , 12697.6488277 , 12094.9288891 ,
        3258.5407439 ,  6475.2187263 ,  8707.97974   , 13476.6833193 ,
       17541.191229  , 33894.9337729 ,  6059.4893361 ,  9559.5295012 ,
        8302.9529783 ,  5731.5628541 ,  5840.0199997 , 19096.4234499 ,
       19201.5622616 ,  3582.0277979 ,  5074.200423  ,  2865.21098206,
       13080.7180305 ,  4916.3605129 ,  7470.7985303 ,  6497.8150063 ,
       15006.6342733 ,  2884.624695  , 15473.0055764 ,  8363.5302732 ,
        3469.550822  , 12811.2685828 ,  6563.1689601 , 20644.3997895 ,
        6524.2646186 ,  4553.0782104 ,  9386.1910761 ,  8397.3894104 ,
       14374.6419254 , 36195.2602486 ,  4912.2613001 ,  8175.1274106 ,
       42809.9114359 ,  4609.2806831 ,  7170.2421017 ,  7135.3037143 ,
        7215.109136  ,  6666.0547326 , 39574.3505763 ,  2526.7234225 ,
        5381.9288277 ,  7421.6914489 , 11972.7980317 ,  6487.7955327 ,
       12485.0550285 ,  3733.64410457,  6996.0587254 ,  6835.6634073 ,
        9224.4317618 ,  1739.45742617,  3604.43400209, 12942.2716664 ,
       11950.440073  ,  5603.3791759 ,  3544.8075539 ,  6097.1610629 ,
        5406.7825557 ,  6309.1151366 ,  5569.0041655 , 12032.0870943 ,
        9750.1606237 , 45870.707645  , 16382.4671257 , 12463.3373468 ,
        3179.0162455 ,  4468.9413639 , 27288.9003594 , 11689.9744769 ,
       11807.1854155 ,  9230.0227544 , 43613.139135  ,  6437.8536441 ])

In [22]:
score = r2_score(y_test,y_pred)
score

0.8708756221232835