In [2]:
import pandas as pd
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

In [3]:
dataset = pd.read_csv("insurance.csv")
dataset

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [4]:
dataset = pd.get_dummies(dataset,drop_first=True)
dataset

,age,bmi,children,charges,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,False,True,False,False,True
1,18,33.770,1,1725.55230,True,False,False,True,False
2,28,33.000,3,4449.46200,True,False,False,True,False
3,33,22.705,0,21984.47061,True,False,True,False,False
4,32,28.880,0,3866.85520,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,True,False,True,False,False
1334,18,31.920,0,2205.98080,False,False,False,False,False
1335,18,36.850,0,1629.83350,False,False,False,True,False
1336,21,25.800,0,2007.94500,False,False,False,False,True
1337,61,29.070,0,29141.36030,False,True,True,False,False

In [5]:
x=dataset[['age','bmi','children','sex_male','smoker_yes','region_northwest','region_southeast','region_southwest']]
y=dataset['charges']

In [6]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=24)

In [7]:
x_train

,age,bmi,children,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
132,53,35.900,2,False,False,False,False,True
508,24,25.270,0,False,False,False,False,False
422,40,32.775,1,True,True,False,False,False
613,34,19.000,3,False,False,False,False,False
1111,38,38.390,3,True,True,False,True,False
...,...,...,...,...,...,...,...,...
145,29,38.830,3,False,False,False,True,False
343,63,36.765,0,True,False,False,False,False
192,25,25.740,0,True,False,False,True,False
899,19,22.515,0,False,False,True,False,False
418,64,39.160,1,True,False,False,True,False

In [8]:
y_train

132     11163.56800
508      3044.21330
422     39125.33225
613      6753.03800
1111    41949.24410
           ...
145      5138.25670
343     13981.85035
192      2137.65360
899      2117.33885
418     14418.28040
Name: charges, Length: 1070, dtype: float64

In [9]:
sc = StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [11]:
para_grid = {'kernel':['linear', 'poly', 'rbf', 'sigmoid'],'gamma':['scale', 'auto'],'C':[10,100,1000,2000,3000]}

In [15]:
grid = GridSearchCV(SVR(),para_grid, refit=True , verbose = 3 ,n_jobs = -1)
grid.fit(x_train , y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['scale', 'auto'],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']},
             verbose=3)

In [17]:

re=grid.cv_results_ 
print("TheR_scorevalueforbestparameter{}:".format(grid.best_params_))

TheR_scorevalueforbestparameter{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}:

In [18]:
table=pd.DataFrame.from_dict(re)

In [19]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.063856,0.004394,0.006359,0.000134,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.351174,0.441399,0.341612,0.426647,0.515385,0.415243,0.063826,25
1,0.050448,0.014316,0.006967,0.000081,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",-0.068772,-0.021016,-0.106836,-0.043248,-0.012596,-0.050493,0.034252,38
2,0.045604,0.003150,0.010571,0.000355,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",-0.080032,-0.035172,-0.126776,-0.063053,-0.029454,-0.066897,0.035160,40
3,0.061733,0.001366,0.013990,0.002133,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",-0.044434,0.011306,-0.084194,-0.014231,0.028157,-0.020679,0.040120,36
4,0.034306,0.001111,0.005903,0.000192,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.351174,0.441399,0.341612,0.426647,0.515385,0.415243,0.063826,25
5,0.033112,0.000972,0.006574,0.000105,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",-0.068778,-0.019956,-0.107225,-0.044099,-0.012379,-0.050488,0.034580,37
6,0.045330,0.003086,0.010935,0.000352,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",-0.080031,-0.035281,-0.126736,-0.062958,-0.029476,-0.066897,0.035125,39
7,0.061300,0.000906,0.012731,0.000239,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.044437,0.011753,-0.084361,-0.014546,0.028258,-0.020666,0.040259,35
8,0.040032,0.000409,0.006023,0.000136,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.546527,0.624675,0.542921,0.602065,0.678737,0.598985,0.050843,19
9,0.035697,0.000326,0.006538,0.000177,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.235458,0.329990,0.245639,0.321750,0.368279,0.300223,0.051293,29
10,0.046359,0.000971,0.010789,0.000291,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.130019,0.204560,0.078164,0.178318,0.240626,0.166337,0.056951,32
11,0.063397,0.000408,0.012935,0.000116,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.371859,0.463834,0.360229,0.448237,0.533699,0.435572,0.063756,24
12,0.040015,0.001184,0.005962,0.000091,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.546527,0.624675,0.542921,0.602065,0.678737,0.598985,0.050843,19
13,0.035858,0.001119,0.006478,0.000103,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.235410,0.336643,0.242566,0.316298,0.369541,0.300092,0.052754,30
14,0.046642,0.001269,0.010849,0.000183,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.130024,0.203787,0.078529,0.178954,0.240443,0.166348,0.056714,31
15,0.062667,0.000420,0.013002,0.000162,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.371839,0.465924,0.361685,0.447053,0.534183,0.436137,0.063713,23
16,0.057179,0.007412,0.005957,0.000085,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.668215,0.654063,0.704264,0.609530,0.666826,0.660580,0.030510,13
17,0.054820,0.005059,0.006521,0.000022,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.694252,0.773963,0.737176,0.738739,0.785584,0.745943,0.032116,9
18,0.058105,0.000893,0.010940,0.000108,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.644844,0.714836,0.597458,0.679608,0.747312,0.676812,0.052427,12
19,0.069108,0.001441,0.012970,0.000168,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.463747,0.506948,0.429524,0.478185,0.605289,0.496739,0.059729,21
20,0.055738,0.006801,0.005964,0.000062,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.668215,0.654063,0.704264,0.609530,0.666826,0.660580,0.030510,13
21,0.052076,0.004133,0.006483,0.000037,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.694241,0.775695,0.736061,0.737790,0.785787,0.745915,0.032588,10
22,0.057648,0.000678,0.010801,0.000144,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.644847,0.714368,0.597800,0.679950,0.747223,0.676838,0.052235,11
23,0.069460,0.001251,0.012953,0.000107,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.464230,0.502082,0.428788,0.491358,0.597214,0.496734,0.056262,22
24,0.076494,0.011902,0.006070,0.000222,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.665873,0.649422,0.705060,0.608454,0.660449,0.657852,0.031019,15
25,0.097208,0.009716,0.006569,0.000094,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.749734,0.812272,0.787556,0.768105,0.819836,0.787501,0.026312,6
26,0.084845,0.010877,0.010873,0.000172,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.757791,0.806690,0.716752,0.755276,0.824441,0.772190,0.038697,8
27,0.070217,0.000940,0.013271,0.000406,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",0.303242,0.333465,0.284511,0.315822,0.435972,0.334602,0.053146,28
28,0.076518,0.011003,0.006052,0.000108,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.665873,0.649422,0.705060,0.608454,0.660449,0.657852,0.031019,15
29,0.092702,0.018009,0.006622,0.000171,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.749720,0.813896,0.787017,0.767424,0.819935,0.787598,0.026756,5
30,0.083876,0.010708,0.010950,0.000208,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.757795,0.806347,0.717073,0.755541,0.824400,0.772231,0.038509,7
31,0.070762,0.001242,0.013024,0.000266,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.282761,0.334723,0.287696,0.348768,0.463099,0.343410,0.065134,27
32,0.095658,0.017730,0.005975,0.000096,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.665736,0.644595,0.707903,0.608436,0.660150,0.657364,0.032215,17
33,0.156502,0.067039,0.006740,0.000206,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.773020,0.831811,0.809370,0.785418,0.829970,0.805918,0.023509,1
34,0.113374,0.012902,0.010855,0.000270,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.779366,0.831722,0.761560,0.779425,0.841674,0.798749,0.031818,4
35,0.069680,0.000819,0.013150,0.000175,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",-0.053927,-0.061920,0.036784,-0.011841,0.062928,-0.005595,0.049069,33
36,0.100818,0.020737,0.006171,0.000201,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.665736,0.644595,0.707903,0.608436,0.660150,0.657364,0.032215,17
37,0.173179,0.050394,0.006614,0.000051,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",0.773017,0.832200,0.809002,0.784259,0.830009,0.805697,0.023799,2
38,0.121834,0.015539,0.010099,0.001612,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.779368,0.831542,0.761728,0.779674,0.841654,0.798793,0.031706,3
39,0.069326,0.004963,0.011089,0.002562,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.053763,-0.090133,0.023638,0.000966,0.038883,-0.016082,0.048565,34

In [20]:
y_pred=grid.predict(x_test)
y_pred

array([41896.58168198, 11207.42512121,  2079.37756678, 40613.43738206,
        7615.41926255, 21694.33563045,  1403.11915521, 11636.90398001,
        5467.37481114, 14146.5168847 , 12469.55764566,  2289.43885617,
       10347.27748383,  5638.93398977,   783.86182876, 27584.75640226,
       21547.27321263,  2392.17578802,  2396.57593693, 32357.85097185,
        8814.66942744, 24040.55680774, 23993.16948697, 31952.94772569,
        2482.98901032, 10295.18838232,  8633.21072459, 39033.04053165,
       12288.52406159, 10517.45234666, 54233.30318179,  6257.5604469 ,
        2449.92395154,  -124.1437504 ,  4993.48851534, 11723.90972226,
       17145.71084374,  6017.9249805 , 13784.78750666, 11898.7628873 ,
        4949.0314975 , 17362.98898397,  5495.01338526,  4794.43308053,
       25467.87455158,  9274.81384601,  5525.45454218, 17291.03849349,
        5900.1801587 ,  1472.62270217,  8417.63955528,  8709.86172549,
        5341.33451721,  3560.74040889, 11294.40535007, 49881.57889421,
       33676.76995458, 44153.89002197,  3882.51576829,  5317.65381821,
       10038.93817876,  1698.18170512,  4344.03263151,  6779.80250922,
        4987.95099491,  7912.08289497,  4977.94411828,  5495.87066366,
        2464.28645306,  8591.72699945,  2817.18002824, 42525.67145316,
        5362.06856932,  3137.84428054,   785.88202896,  9533.4785247 ,
       33663.6187247 ,  7239.65032816, 10428.67469568, 12175.20374621,
        6127.98239071, 28257.35607656,  5042.07045935,  8943.11427443,
       26527.77339127,  7284.12608556,  7007.60375126,  8140.24654514,
        8367.5759625 ,  1549.62457206, 10856.2683993 ,  9898.26742733,
       44617.11867117,  4382.20371765,  3551.70901333, 38152.50965341,
        2467.3650753 , 13807.23209776,  1616.10106038,  2206.01413757,
        3350.62849657,  4123.12383003,  9499.85429311,  2784.64813171,
        1180.93445399,  4171.57999027, 37916.93881667,  7383.37045274,
        9851.43022497,  2751.46568793,  8932.64288389, 11007.62857733,
       13074.02047529,   447.18871348, 20793.13874762,  8677.98501171,
        9191.52304098, 21301.84714523, 10848.70382629, 35089.46944338,
        2999.87276778, 10946.53856716,  8023.42965857,  5560.15592138,
        8872.67553022, 23033.97114119,  5537.37120176,  7633.07425448,
        6012.13911675,  8437.85144723,  9153.49233109,  7724.31268212,
       11161.16423122, 10161.66232159, 41753.08105673,  3675.73417975,
        7383.70137137,  7787.72161839,  4130.97579098,  9423.15266698,
       14134.97273537,  5387.95749814,  8543.60750277, 25911.81690402,
        4327.34194163,  9901.18258347,  4752.89251449, 51242.81737006,
       13447.31129368,  8753.37619091,  1517.5214145 ,  7099.28183622,
        2960.94956278, 12036.3344851 ,  8579.98105286,  5236.32709408,
        4269.53672941,  2750.65296214, 34965.5232837 ,  1896.53639117,
       11452.95644415, 31632.28726656, 30092.53446039,  4750.65961569,
       31656.76232581,  1152.24941511, 11605.77846923,  1115.55519041,
       -4808.74673662,  8880.08042463, 11387.7863881 ,  1988.85712366,
         703.37210855,  1306.74195038,  7815.43269932,  9938.07071664,
        6463.05333885,  1554.47982844,  4805.77243536,  4937.04280347,
       35989.78327941, 12874.67094622,  7989.97858009, 12441.19222042,
        9390.68456003,  9547.836226  , 34090.19236298, 39927.79996016,
       25283.4663094 , 21980.736483  , 10810.14563114, 10207.4013812 ,
        4076.4193407 ,  3413.95562897,  7766.211065  , 10963.07767018,
       20115.8546794 , 31519.70396707,  5584.19533507,  9501.6630647 ,
        8116.80403234,  4985.14530254,  3713.22697746, 16048.10185731,
       24049.82165783,  3701.11371456,  6276.29527713,  1831.50333718,
        7335.8665905 ,  3423.25306583,  4909.34830572,  6010.53807928,
       12167.70259125,   971.15411163, 12506.81257792,  7269.07088682,
        1568.61201705,  9516.78812582,  7574.02847424, 24457.08071699,
        4600.05475588,  2436.1123844 ,  6880.26121107,  5667.17624783,
       13195.65589741, 28989.10545177,  3727.47959284,  6193.90310919,
       38430.90992429,  4751.35670176,  7307.98091267,  8167.89301101,
        4685.06062113,  5064.61707714, 34820.50192735,  1843.8494775 ,
        5785.39223998,  6865.48632905, 11529.70891045,  6076.55063934,
       11477.04051243,  4234.68457194,  6483.69898025,  6236.41397333,
        -527.128564  ,  1197.75574307,  4077.9955274 ,  9278.37553769,
       10430.47788126,  6092.18810428,  3373.18718129,  5345.32075306,
        5099.80722883,  4904.82168266,  3106.1999317 , 11416.88000729,
       10099.86481429, 42691.91708109, 11783.63210774, 10690.59731772,
        3179.35258405,  3351.63893242, 27029.37606455, 10631.04321602,
       10006.33200171,  8809.78437643, 44034.55470327,  4156.92800183])

In [21]:
score = r2_score(y_test,y_pred)
score

0.8414750342580379