In [27]:
import pandas as pd

In [28]:
dataset = pd.read_csv("Placement.csv")
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [29]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sl_no           215 non-null    int64
 1   gender          215 non-null    str
 2   ssc_p           215 non-null    float64
 3   ssc_b           215 non-null    str
 4   hsc_p           215 non-null    float64
 5   hsc_b           215 non-null    str
 6   hsc_s           215 non-null    str
 7   degree_p        215 non-null    float64
 8   degree_t        215 non-null    str
 9   workex          215 non-null    str
 10  etest_p         215 non-null    float64
 11  specialisation  215 non-null    str
 12  mba_p           215 non-null    float64
 13  status          215 non-null    str
 14  salary          148 non-null    float64
dtypes: float64(6), int64(1), str(8)
memory usage: 35.0 KB

In [30]:
dataset.isnull().sum()

sl_no              0
gender             0
ssc_p              0
ssc_b              0
hsc_p              0
hsc_b              0
hsc_s              0
degree_p           0
degree_t           0
workex             0
etest_p            0
specialisation     0
mba_p              0
status             0
salary            67
dtype: int64

In [31]:
for columnNames in dataset.columns:
    print(columnNames)

sl_no
gender
ssc_p
ssc_b
hsc_p
hsc_b
hsc_s
degree_p
degree_t
workex
etest_p
specialisation
mba_p
status
salary

In [32]:
print(dataset["gender"].dtypes)

str

In [33]:
print(dataset.dtypes)

sl_no               int64
gender                str
ssc_p             float64
ssc_b                 str
hsc_p             float64
hsc_b                 str
hsc_s                 str
degree_p          float64
degree_t              str
workex                str
etest_p           float64
specialisation        str
mba_p             float64
status                str
salary            float64
dtype: object

In [34]:
quan=[] #numerical
qual=[] #categorical

for columnNames in dataset.columns:
    if(dataset[columnNames].dtype =="str"):
        qual.append(columnNames)
    else:
        quan.append(columnNames)

In [35]:
print(qual)

['gender', 'ssc_b', 'hsc_b', 'hsc_s', 'degree_t', 'workex', 'specialisation', 'status']

In [36]:
print(quan)

['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

In [37]:
dataset.describe()

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
count,215.000000,215.000000,215.000000,215.000000,215.000000,215.000000,148.000000
mean,108.000000,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
std,62.209324,10.827205,10.897509,7.358743,13.275956,5.833385,93457.452420
min,1.000000,40.890000,37.000000,50.000000,50.000000,51.210000,200000.000000
25%,54.500000,60.600000,60.900000,61.000000,60.000000,57.945000,240000.000000
50%,108.000000,67.000000,65.000000,66.000000,71.000000,62.000000,265000.000000
75%,161.500000,75.700000,73.000000,72.000000,83.500000,66.255000,300000.000000
max,215.000000,89.400000,97.700000,91.000000,98.000000,77.890000,940000.000000

In [38]:
descriptive=pd.DataFrame(index=["Mean","Median","Mode","Min","25%","50%","75%","Max"],columns=quan)
descriptive

       sl_no ssc_p hsc_p degree_p etest_p mba_p salary
Mean     NaN   NaN   NaN      NaN     NaN   NaN    NaN
Median   NaN   NaN   NaN      NaN     NaN   NaN    NaN
Mode     NaN   NaN   NaN      NaN     NaN   NaN    NaN
Min      NaN   NaN   NaN      NaN     NaN   NaN    NaN
25%      NaN   NaN   NaN      NaN     NaN   NaN    NaN
50%      NaN   NaN   NaN      NaN     NaN   NaN    NaN
75%      NaN   NaN   NaN      NaN     NaN   NaN    NaN
Max      NaN   NaN   NaN      NaN     NaN   NaN    NaN

In [39]:
print(dataset["salary"].median())

265000.0

In [40]:
descriptive = pd.DataFrame(index = ["Mean", "Median", "Mode", "Min", "25%", "50%", "75%", "Max","IQR","1.5IQR","LesserOutlier","GreaterOutlier"], columns=quan)
for columnName in quan:
    descriptive.loc["Mean", columnName] = dataset[columnName].mean()
    descriptive.loc["Median",columnName] = dataset[columnName].median()
    descriptive.loc["Mode",columnName] = dataset[columnName].mode()[0]
    descriptive.loc["Min",columnName] = dataset.describe()[columnName]["min"]
    descriptive.loc["25%",columnName] = dataset.describe()[columnName]["25%"]
    descriptive.loc["50%",columnName] = dataset.describe()[columnName]["50%"]
    descriptive.loc["75%",columnName] = dataset.describe()[columnName]["75%"]
    descriptive.loc["Max",columnName] = dataset.describe()[columnName]["max"]
    descriptive.loc["IQR",columnName] = dataset.describe()[columnName]["75%"] - dataset.describe()[columnName]["25%"]
    descriptive.loc["1.5IQR",columnName] =  1.5 * descriptive[columnName]["IQR"]
    descriptive.loc["LesserOutlier",columnName] = dataset.describe()[columnName]["25%"] - descriptive[columnName]["1.5IQR"]
    descriptive.loc["GreaterOutlier",columnName] = dataset.describe()[columnName]["75%"] + descriptive[columnName]["1.5IQR"]

In [41]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Min,1.0,40.89,37.0,50.0,50.0,51.21,200000.0
25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
Max,215.0,89.4,97.7,91.0,98.0,77.89,940000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5IQR,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
LesserOutlier,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
GreaterOutlier,322.0,98.35,91.15,88.5,118.75,78.72,390000.0

In [42]:
lesser=[]
greater=[]
for columnNames in quan:
    if descriptive[columnNames]["LesserOutlier"] > descriptive[columnNames]["Min"]:
        lesser.append(columnNames)
    if descriptive[columnNames]["GreaterOutlier"] < descriptive[columnNames]["Max"]:
        greater.append(columnNames)

In [43]:
lesser

['hsc_p']

In [44]:
greater

['hsc_p', 'degree_p', 'salary']

In [45]:

for lesscolumn in lesser:
    dataset.loc[dataset[lesscolumn] < descriptive.loc["LesserOutlier", lesscolumn], lesscolumn] = descriptive.loc["LesserOutlier", lesscolumn]

for greatcolumn in greater:
    dataset.loc[dataset[greatcolumn] > descriptive.loc["GreaterOutlier", greatcolumn], greatcolumn] = descriptive.loc["GreaterOutlier", greatcolumn]

In [46]:
descriptive = pd.DataFrame(index = ["Mean", "Median", "Mode", "Min", "25%", "50%", "75%", "Max","IQR","1.5IQR","LesserOutlier","GreaterOutlier"], columns=quan)
##descriptive["Mean"]["salary"]=0
for columnName in quan:
    descriptive.loc["Mean", columnName] = dataset[columnName].mean()
    descriptive.loc["Median",columnName] = dataset[columnName].median()
    descriptive.loc["Mode",columnName] = dataset[columnName].mode()[0]
    descriptive.loc["Min",columnName] = dataset.describe()[columnName]["min"]
    descriptive.loc["25%",columnName] = dataset.describe()[columnName]["25%"]
    descriptive.loc["50%",columnName] = dataset.describe()[columnName]["50%"]
    descriptive.loc["75%",columnName] = dataset.describe()[columnName]["75%"]
    descriptive.loc["Max",columnName] = dataset.describe()[columnName]["max"]
    descriptive.loc["IQR",columnName] = dataset.describe()[columnName]["75%"] - dataset.describe()[columnName]["25%"]
    descriptive.loc["1.5IQR",columnName] =  1.5 * descriptive[columnName]["IQR"]
    descriptive.loc["LesserOutlier",columnName] = dataset.describe()[columnName]["25%"] - descriptive[columnName]["1.5IQR"]
    descriptive.loc["GreaterOutlier",columnName] = dataset.describe()[columnName]["75%"] + descriptive[columnName]["1.5IQR"]

In [47]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.334744,66.358558,72.100558,62.278186,277648.648649
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Min,1.0,40.89,42.75,50.0,50.0,51.21,200000.0
25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
Max,215.0,89.4,91.15,88.5,98.0,77.89,390000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5IQR,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
LesserOutlier,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
GreaterOutlier,322.0,98.35,91.15,88.5,118.75,78.72,390000.0

In [48]:
lesser1=[]
greater1=[]
for columnNames in quan:
    if descriptive[columnNames]["LesserOutlier"] > descriptive[columnNames]["Min"]:
        lesser.append(columnNames)
    if descriptive[columnNames]["GreaterOutlier"] < descriptive[columnNames]["Max"]:
        greater.append(columnNames)

In [49]:
lesser1

[]

In [50]:
greater1

[]

In [51]:
dataset.to_csv("preprocessed_dataset.csv", index=False)

In [53]:
import pandas as pd

original = pd.read_csv("Placement.csv")
processed = pd.read_csv("preprocessed_dataset.csv")

In [56]:
print("Original salary:")
display(original["salary"].describe())

print("Processed salary:")
display(processed["salary"].describe())

Original salary:

count       148.000000
mean     288655.405405
std       93457.452420
min      200000.000000
25%      240000.000000
50%      265000.000000
75%      300000.000000
max      940000.000000
Name: salary, dtype: float64

Processed salary:

count       148.000000
mean     277648.648649
std       54264.139179
min      200000.000000
25%      240000.000000
50%      265000.000000
75%      300000.000000
max      390000.000000
Name: salary, dtype: float64